services:
    newscoop_topicmanagement_plugin.lifecyclesubscriber:
        class: Newscoop\TopicManagementPluginBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
        tags:
            - { name: kernel.event_subscriber}

    newscoop_topicmanagement_plugin.configure_menu_listener:
        class: Newscoop\TopicManagementPluginBundle\EventListener\ConfigureMenuListener
        tags:
            - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }
        arguments: 
            - @translator