services:
    newscoop_topicmanagement_plugin.lifecyclesubscriber:
        class: Newscoop\TopicManagementPluginBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
        tags:
            - { name: kernel.event_subscriber}

    newscoop_topicmanagement_plugin.service:
        class: Newscoop\TopicManagementPluginBundle\Services\TopicManagementService
        arguments: ["@em"]